FROM node:18-slim AS builder

RUN apt-get update -y \
  && apt-get install -y openssl

WORKDIR /usr/app

COPY package.json yarn.lock /usr/app/

RUN yarn

COPY . .

RUN yarn prisma generate

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

ARG ADMIN_API_PORT
ENV ADMIN_API_PORT $ADMIN_API_PORT

ARG CUSTOMER_API_PORT
ENV CUSTOMER_API_PORT $CUSTOMER_API_PORT

ARG ADMIN_FRONTEND_HOSTNAME
ENV ADMIN_FRONTEND_HOSTNAME $ADMIN_FRONTEND_HOSTNAME

ARG BUSINESS_PORT
ENV BUSINESS_PORT $BUSINESS_PORT

ARG BUSINESS_FRONTEND_HOSTNAME
ENV BUSINESS_FRONTEND_HOSTNAME $BUSINESS_FRONTEND_HOSTNAME

ARG PUBLIC_API_PORT
ENV PUBLIC_API_PORT $PUBLIC_API_PORT

ARG PUBLIC_FRONTEND_HOSTNAME
ENV PUBLIC_FRONTEND_HOSTNAME $PUBLIC_FRONTEND_HOSTNAME

ARG DEFAULT_ADMIN_EMAIL
ENV DEFAULT_ADMIN_EMAIL $DEFAULT_ADMIN_EMAIL

ARG DEFAULT_ADMIN_PASSWORD
ENV DEFAULT_ADMIN_PASSWORD $DEFAULT_ADMIN_PASSWORD

ARG S3_BUCKET
ENV S3_BUCKET $S3_BUCKET

ARG S3_REGION
ENV S3_REGION $S3_REGION

ARG S3_ACCESS_KEY
ENV S3_ACCESS_KEY $S3_ACCESS_KEY

ARG S3_SECRET_KEY
ENV S3_SECRET_KEY $S3_SECRET_KEY

ARG DATABASE_URL
ENV DATABASE_URL $DATABASE_URL

ARG DATABASE_READ_REPLICA_URL
ENV DATABASE_READ_REPLICA_URL $DATABASE_READ_REPLICA_URL

ARG GOOGLE_APPLICATION_CREDENTIALS
ENV GOOGLE_APPLICATION_CREDENTIALS $GOOGLE_APPLICATION_CREDENTIALS

ARG REDIS_URL
ENV REDIS_URL $REDIS_URL

ARG STRIPE_SECRET_KEY
ENV STRIPE_SECRET_KEY $STRIPE_SECRET_KEY

ARG STRIPE_WEBHOOK_SECRET
ENV STRIPE_WEBHOOK_SECRET $STRIPE_WEBHOOK_SECRET

ARG SMTP_HOST_NAME
ENV SMTP_HOST_NAME $SMTP_HOST_NAME

ARG SMTP_PORT
ENV SMTP_PORT $SMTP_PORT

ARG SMTP_USERNAME
ENV SMTP_USERNAME $SMTP_USERNAME

ARG SMTP_PASSWORD
ENV SMTP_PASSWORD $SMTP_PASSWORD

ARG SENDER_EMAIL
ENV SENDER_EMAIL $SENDER_EMAIL

ARG TESTER_EMAIL
ENV TESTER_EMAIL $TESTER_EMAIL

ARG TESTER_PASSWORD
ENV TESTER_PASSWORD $TESTER_PASSWORD

ARG DATABASE_ENCRYPTION_KEY
ENV DATABASE_ENCRYPTION_KEY $DATABASE_ENCRYPTION_KEY

RUN yarn build

FROM builder AS business_api
COPY --from=builder /usr/app ./app
EXPOSE ${BUSINESS_PORT}

FROM builder AS public_api
COPY --from=builder /usr/app ./app
EXPOSE ${PUBLIC_API_PORT}

FROM builder AS admin_api
COPY --from=builder /usr/app ./app
EXPOSE ${ADMIN_API_PORT}
