export type CityData = {
  name: string;
};

export const SabahCities: CityData[] = [
  { name: 'Beaufort' },
  { name: 'Beluran' },
  { name: 'Bongawan' },
  { name: 'Inanam' },
  { name: 'Keningau' },
  { name: 'Kiansom' },
  { name: 'Kota Belud' },
  { name: 'Kota Kinabalu' },
  { name: 'Kota Kinabatangan' },
  { name: 'Kota Marudu' },
  { name: 'Kuala Penyu' },
  { name: 'Kudat' },
  { name: 'Kunak' },
  { name: 'Lahad Datu' },
  { name: 'Likas' },
  { name: 'Luyang' },
  { name: 'Membakut' },
  { name: 'Menumbok' },
  { name: 'Nabawan' },
  { name: 'Pamol' },
  { name: 'Papar' },
  { name: 'Penampang' },
  { name: 'Pitas' },
  { name: 'Putatan' },
  { name: 'Ranau' },
  { name: 'Sandakan' },
  { name: 'Semporna' },
  { name: 'Sipitang' },
  { name: 'Tambunan' },
  { name: 'Tamparuli' },
  { name: 'Tawau' },
  { name: 'Telipok' },
  { name: 'Tenom' },
  { name: 'Tuaran' },
  { name: 'Others' },
  { name: 'Telupid' },
];
